package org.cloud4fun.myjobs.server.hibernate;

// Generated May 7, 2012 6:31:57 AM by Hibernate Tools 3.4.0.CR1

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Integer id;
	private String project;

	public Project() {
	}

	public Project(String project) {
		this.project = project;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

}
