package org.cloud4fun.myjobs.server.hibernate;

// Generated May 7, 2012 6:31:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Task generated by hbm2java
 */
public class Task implements java.io.Serializable {

	private Integer id;
	private String task;
	private Integer dur;
	private Boolean finished;
	private Date due;

	public Task() {
	}

	public Task(Date due) {
		this.due = due;
	}

	public Task(String task, Integer dur, Boolean finished, Date due) {
		this.task = task;
		this.dur = dur;
		this.finished = finished;
		this.due = due;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTask() {
		return this.task;
	}

	public void setTask(String task) {
		this.task = task;
	}

	public Integer getDur() {
		return this.dur;
	}

	public void setDur(Integer dur) {
		this.dur = dur;
	}

	public Boolean getFinished() {
		return this.finished;
	}

	public void setFinished(Boolean finished) {
		this.finished = finished;
	}

	public Date getDue() {
		return this.due;
	}

	public void setDue(Date due) {
		this.due = due;
	}

}
