package org.cloud4fun.myjobs.server.hibernate;

// Generated May 7, 2012 6:31:57 AM by Hibernate Tools 3.4.0.CR1

/**
 * TaskProjectRel generated by hbm2java
 */
public class TaskProjectRel implements java.io.Serializable {

	private Integer id;
	private Integer taskId;
	private Integer projectId;

	public TaskProjectRel() {
	}

	public TaskProjectRel(Integer taskId, Integer projectId) {
		this.taskId = taskId;
		this.projectId = projectId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

}
