package org.cloud4fun.myjobs.server.hibernate;

// Generated May 7, 2012 6:31:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WorkUnit generated by hbm2java
 */
public class WorkUnit implements java.io.Serializable {

	private Integer id = null;
	private Integer taskId;
	private Date workedOn = null;

	public WorkUnit() {
	}

	public WorkUnit(Date workedOn) {
		this.workedOn = workedOn;
	}

	public WorkUnit(Integer taskId, Date workedOn) {
		this.taskId = taskId;
		this.workedOn = workedOn;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	public Date getWorkedOn() {
		return this.workedOn;
	}

	public void setWorkedOn(Date workedOn) {
		this.workedOn = workedOn;
	}

}
